### ISSUE TITLE
perfectionist forces order or "args"

### ISSUE THREAD

**Issue by jbbarth** [oclif/eslint-config-oclif-typescript#115]
Take this command args definition:

```typescript
export default class Shell extends Command {
  static args = {
    machine: Args.string({description: 'Machine'}),
    command: Args.string({description: 'Command to run'}),
  }
}
```
It's desirable to have arguments in that order, but perfectionist's "sort-object" rule will reorder and put the "command" arg first.

Have you come across this problem? Do you have a recommendation about how to workaround it? Thanks

**Comment by mdonnalley** [comment]
@jbbarth Thanks for pointing this out. We haven't run into it ourselves since we don't use args all too often - and when we do it's typically a single arg

I'll look into solutions but you can always disable the rule with `// eslint-disable-next-line perfectionist/sort-objects`

**Comment by mdonnalley** [comment]
There's an `ignore-pattern` option on the `sort-objects` class but unfortunately it doesn't look like it applies to class properties

If this is something you need I'd recommend one of the following:
- Disable the rule inline (as described above) or in your project's eslint configuration
- Create an issue on the eslint-plugin-perfectionist repo
- Do the following:

Use the `ingore-pattern` option to ignore any variable called `args`
```javascript
module.exports = {
  rules: [
    'perfectionist/sort-objects': [
      'error',
      {
        'ignore-pattern': ['args']
      }
    ],
  ]
}
```

In your command class, define your args like this:

```typescript
import {Args, Command} from '@oclif/core'

const args = {
  bArg: Args.string(),
  aArg: Args.string()
}

export default class MyCmd extends Command {
  static args = args
}
```
