### ISSUE TITLE
Typescript eslint issue on decorators

### ISSUE THREAD

**Issue by RDeluxe** [oclif/eslint-config-oclif-typescript#52]
Hello there,

Decorators are throwing errors with eslint + TS 4.8.0

Solution is to bump the version of the typescript eslint plugin : https://github.com/typescript-eslint/typescript-eslint/issues/5525#issuecomment-1226256085

**Comment by mdonnalley** [comment]
Closing since the latest version is using `@typescript-eslint/eslint-plugin@^6`, which has the fix
